name: CI

env:
  CI: false

on:
  push:
    branches: [ master ]

permissions: 
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: ESLintCode
        uses: actions/setup-node@v2
      - run: yarn
      - run: npm install -g eslint && eslint ./src/*/**.js

      - name: StyleLintCode
        uses: actions/setup-node@v2
      - run: npm install -g stylelint stylelint-less
      - run: mkdir .tmp-css-check && touch .tmp-css-check/.stylelintrc.json && echo '{"plugins":["stylelint-less"],"rules":{}}' >> .tmp-css-check/.stylelintrc.json && stylelint "src/**/*.less" --config .tmp-css-check/.stylelintrc.json --aei

  Deploy:
    needs: Check
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build
        uses: actions/setup-node@v2
        # env:
        #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        #   BRANCH: main
      - run: npm install
      - run: npm run build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build